### ISSUE TITLE
https://registry.npmjs.org/node-unofficialmxm 404

### ISSUE THREAD

**Issue by chesty** [Quacky2200/Spotify-Web-Player-for-Linux#58]
I think node-unofficialmxm has gone awal,
I'm assuming you can fix that, but out of curiosity, how or where would I install it manually? 

I tried putting it in lots (all?) of node_modules directories I
could find, but spotifywebplayer still couldn't find it.
I don't know node, maybe I needed to update an index or something?

**Comment by Quacky2200** [comment]
Depends, what kind of things are actually wrong? 

Installation wise, you need to pull from GitHub, either using git or npm, you can search how to include a Git repo using npm on Google, it's quite simple. Otherwise, you can just download the repo from GitHub directly and use it in Node.JS

There's also a bug in v1.0.0 where lyrics just don't load at all (shows as loading), it's fixed in the latest sync but hasn't been released yet as I have been busy and never got round to perfecting the version. I also never released node-unofficialmxm to npmjs.org and you will be able to find it here [Quacky2200 node-unofficialmxm Repository](https://github.com/Quacky2200/node-unofficialmxm).

If you think the module is faulty, you could just download the repo into a folder placed inside `node_modules` called `node-unofficialmxm`. Upon reloading SWP, it should use the new library. If you're using v1.0.0, I would recommend trying out the unstable sync'd version since the lyrics should load better than in v1.0.0

Hope that helps you out for now :smile:

**Comment by chesty** [comment]
Thanks Mathew,
sorry for the vague report

I'm using the git master version (comment Fix #55)

I ran ./make_deb.sh x86_64

installed the deb,  it downloaded a bunch of archives during install, I think node and electron

ran /usr/bin/spotifywebplayer/spotifywebplayer

and get

Error: Cannot find module 'node-unofficialmxm'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/usr/bin/spotifywebplayer/libs/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/bin/spotifywebplayer/app.js:6:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'node-unofficialmxm'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/usr/bin/spotifywebplayer/libs/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/bin/spotifywebplayer/app.js:6:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)


I have installed node-unofficialmxm with

npm install -g

in a git cloned node-unofficialmxm 

I also tried copying it in all the node_modules directories I could find /usr/bin/spotifywebplayer

**Comment by chesty** [comment]
I followed the manual install instructions in README.md and it worked OK.
good enough for me.
cheers. thanks for your work.

**Comment by Quacky2200** [comment]
Ahh glad you were able to sort it out :+1:
