### ISSUE TITLE
javascript errors in tray.js

### ISSUE THREAD

**Issue by janvanbesien** [Quacky2200/Spotify-Web-Player-for-Linux#61]
When I click any of the options in the tray menu, I get this.

`Uncaught Exception:
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: tray.js:50:37.
    at callIntoRenderer (/usr/bin/spotifywebplayer/libs/electron/resources/electron.asar/browser/rpc-server.js:189:19)
    at MenuItem.click (/usr/bin/spotifywebplayer/libs/electron/resources/electron.asar/browser/api/menu-item.js:59:9)
    at Function.executeCommand (/usr/bin/spotifywebplayer/libs/electron/resources/electron.asar/browser/api/menu.js:121:15)
`
This is on ubuntu 16.10 with the 1.0.0 stable deb package.

**Comment by Quacky2200** [comment]
That normally happens when the window has been closed but the application/tray hasn't quit yet. It shouldn't happen on the latest but until that I release the next version, you won't be on stable software. Sadly I'm in the midst of a big change so that I can release an AppImage/Snap packages on the next version

**Comment by Quacky2200** [comment]
I will close this for now because this bug shouldn't be present after the 1.0.0 git pushes
