### ISSUE TITLE
 version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by fillipeweb** [Quacky2200/Spotify-Web-Player-for-Linux#70]
I've been got this error when I open the spotify web player:

Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /opt/Spotify Web Player for Linux/resources/app.asar.unpacked/node_modules/dbus/build/Release/dbus.node)
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/Spotify Web Player for Linux/resources/app.asar/node_modules/dbus/lib/dbus.js:3:13)

**Comment by Quacky2200** [comment]
It seems to be an issue with the version of GLIBCXX installed, I'm not sure why it would need to be installed as it seems like it would be more of something you'd get when compiled. Anyway, try installing libstdc++ or libstdc++6 and see how you get on. I've never had this issue before and I think it may just be a dependency requirement or some kind of version difference if you have been installing various PPA's, updates etc.

**Comment by knocatomi** [comment]
I am getting the same error on a debian 8.7 x64 machine. I get this when tring to install ibstdc++ or libstdc++6:
```
aptget libstdc++
Couldn't find package "libstdc+".  However, the following packages contain "libstdc+" in their name:
```
```
aptget libstdc++6
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
```
