### ISSUE TITLE
node-gyp/dbus error when installing with npm

### ISSUE THREAD

**Issue by Jazzelhawk** [Quacky2200/Spotify-Web-Player-for-Linux#81]
So I'm trying to install 1.0.35 by doing ``npm install`` and this is the output:
```
root@Aspire-ES1-522:/usr/bin/spotifywebplayer# npm install
npm WARN prefer global node-gyp@3.5.0 should be installed with -g

> abstract-socket@1.1.0 install /usr/bin/spotifywebplayer/node_modules/abstract-socket
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.7.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/bin/spotifywebplayer/node_modules/abstract-socket/.node-gyp"
make: Entering directory '/usr/bin/spotifywebplayer/node_modules/abstract-socket/build'
  CXX(target) Release/obj.target/abstract_socket/src/abstract_socket.o
  SOLINK_MODULE(target) Release/obj.target/abstract_socket.node
  COPY Release/abstract_socket.node
make: Leaving directory '/usr/bin/spotifywebplayer/node_modules/abstract-socket/build'

> dbus@0.2.23 install /usr/bin/spotifywebplayer/node_modules/dbus
> node-gyp configure build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.7.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/bin/spotifywebplayer/node_modules/dbus/.node-gyp"
/bin/sh: 1: pkg-config: not found
gyp: Call to 'pkg-config  --libs-only-l --libs-only-other dbus-1' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.8.0-41-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/bin/spotifywebplayer/node_modules/dbus
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
spotifywebplayer@1.0.30 /usr/bin/spotifywebplayer
├─┬ auto-launch@4.0.1 
│ ├── applescript@1.0.0 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ ├─┬ untildify@2.1.0 
│ │ └── os-homedir@1.0.2 
│ └── winreg@1.0.1 
├─┬ electron@1.4.2 
│ ├─┬ electron-download@3.3.0 
│ │ ├─┬ fs-extra@0.30.0 
│ │ │ ├── jsonfile@2.4.0 
│ │ │ ├── klaw@1.3.1 
│ │ │ └── path-is-absolute@1.0.1 
│ │ ├── home-path@1.0.3 
│ │ ├── minimist@1.2.0 
│ │ ├─┬ nugget@2.0.1 
│ │ │ ├── minimist@1.2.0 
│ │ │ ├─┬ pretty-bytes@1.0.4 
│ │ │ │ ├── get-stdin@4.0.1 
│ │ │ │ └─┬ meow@3.7.0 
│ │ │ │   ├── camelcase-keys@2.1.0 
│ │ │ │   ├─┬ loud-rejection@1.6.0 
│ │ │ │   │ └─┬ currently-unhandled@0.4.1 
│ │ │ │   │   └── array-find-index@1.0.2 
│ │ │ │   ├── map-obj@1.0.1 
│ │ │ │   ├── minimist@1.2.0 
│ │ │ │   ├─┬ redent@1.0.0 
│ │ │ │   │ ├── indent-string@2.1.0 
│ │ │ │   │ └── strip-indent@1.0.1 
│ │ │ │   └── trim-newlines@1.0.0 
│ │ │ ├─┬ progress-stream@1.2.0 
│ │ │ │ ├── speedometer@0.1.4 
│ │ │ │ └─┬ through2@0.2.3 
│ │ │ │   ├─┬ readable-stream@1.1.14 
│ │ │ │   │ └── isarray@0.0.1 
│ │ │ │   └─┬ xtend@2.1.2 
│ │ │ │     └── object-keys@0.4.0 
│ │ │ ├── single-line-log@1.1.2 
│ │ │ └── throttleit@0.0.2 
│ │ ├─┬ path-exists@2.1.0 
│ │ │ └─┬ pinkie-promise@2.0.1 
│ │ │   └── pinkie@2.0.4 
│ │ ├─┬ rc@1.1.7 
│ │ │ ├── deep-extend@0.4.1 
│ │ │ ├── minimist@1.2.0 
│ │ │ └── strip-json-comments@2.0.1 
│ │ └─┬ sumchecker@1.3.0 
│ │   └── es6-promise@4.1.0 
│ └─┬ extract-zip@1.6.0 
│   ├─┬ concat-stream@1.5.0 
│   │ ├── inherits@2.0.3 
│   │ ├─┬ readable-stream@2.0.6 
│   │ │ ├── core-util-is@1.0.2 
│   │ │ ├── isarray@1.0.0 
│   │ │ ├── process-nextick-args@1.0.7 
│   │ │ ├── string_decoder@0.10.31 
│   │ │ └── util-deprecate@1.0.2 
│   │ └── typedarray@0.0.6 
│   ├── debug@0.7.4 
│   ├── mkdirp@0.5.0 
│   └─┬ yauzl@2.4.1 
│     └─┬ fd-slicer@1.0.1 
│       └── pend@1.2.0 
├─┬ electron-builder@15.2.0 
│ ├─┬ 7zip-bin@2.0.4 
│ │ └── 7zip-bin-linux@1.0.3 
│ ├─┬ UNMET PEER DEPENDENCY ajv@5.0.3-beta.0
│ │ ├── co@4.6.0 
│ │ └─┬ json-stable-stringify@1.0.1 
│ │   └── jsonify@0.0.0 
│ ├── ajv-keywords@2.0.1-beta.1 
│ ├── bluebird-lst@1.0.1 
│ ├─┬ chalk@1.1.3 
│ │ ├── ansi-styles@2.2.1 
│ │ ├── escape-string-regexp@1.0.5 
│ │ ├─┬ has-ansi@2.0.0 
│ │ │ └── ansi-regex@2.1.1 
│ │ ├── strip-ansi@3.0.1 
│ │ └── supports-color@2.0.0 
│ ├── chromium-pickle-js@0.2.0 
│ ├── cuint@0.2.2 
│ ├── electron-builder-core@15.2.0 
│ ├─┬ electron-builder-http@15.0.1 
│ │ └── debug@2.6.1 
│ ├─┬ electron-builder-util@15.2.0 
│ │ ├── debug@2.6.1 
│ │ ├── ini@1.3.4 
│ │ ├─┬ node-emoji@1.5.1 
│ │ │ └── string.prototype.codepointat@0.2.0 
│ │ ├─┬ source-map-support@0.4.11 
│ │ │ └── source-map@0.5.6 
│ │ └── stat-mode@0.2.2 
│ ├─┬ electron-download-tf@4.0.0 
│ │ ├── fs-extra@2.0.0 
│ │ ├── minimist@1.2.0 
│ │ ├── path-exists@3.0.0 
│ │ └── sumchecker@2.0.1 
│ ├─┬ electron-macos-sign@1.6.0 
│ │ └── compare-version@0.1.2 
│ ├─┬ electron-publish@15.2.0 
│ │ ├── mime@1.3.4 
│ │ └── progress-ex@2.0.0 
│ ├─┬ fs-extra-p@4.0.2 
│ │ └── fs-extra@2.0.0 
│ ├── hosted-git-info@2.2.0 
│ ├─┬ is-ci@1.0.10 
│ │ └── ci-info@1.0.0 
│ ├── isbinaryfile@3.0.2 
│ ├─┬ js-yaml@3.8.2 
│ │ ├─┬ argparse@1.0.9 
│ │ │ └── sprintf-js@1.0.3 
│ │ └── esprima@3.1.3 
│ ├─┬ minimatch@3.0.3 
│ │ └─┬ brace-expansion@1.1.6 
│ │   ├── balanced-match@0.4.2 
│ │   └── concat-map@0.0.1 
│ ├── node-forge@0.7.0 
│ ├─┬ normalize-package-data@2.3.6 
│ │ ├─┬ is-builtin-module@1.0.0 
│ │ │ └── builtin-modules@1.1.1 
│ │ └─┬ validate-npm-package-license@3.0.1 
│ │   ├─┬ spdx-correct@1.0.2 
│ │   │ └── spdx-license-ids@1.2.2 
│ │   └── spdx-expression-parse@1.0.4 
│ ├─┬ parse-color@1.0.0 
│ │ └── color-convert@0.5.3 
│ ├─┬ plist@2.0.1 
│ │ ├── base64-js@1.1.2 
│ │ ├── xmlbuilder@8.2.2 
│ │ └── xmldom@0.1.27 
│ ├── semver@5.3.0 
│ ├─┬ update-notifier@2.1.0 
│ │ ├─┬ boxen@1.0.0 
│ │ │ ├── ansi-align@1.1.0 
│ │ │ ├── camelcase@4.0.0 
│ │ │ ├── cli-boxes@1.0.0 
│ │ │ ├─┬ string-width@2.0.0 
│ │ │ │ └── is-fullwidth-code-point@2.0.0 
│ │ │ ├─┬ term-size@0.1.1 
│ │ │ │ └─┬ execa@0.4.0 
│ │ │ │   ├─┬ cross-spawn-async@2.2.5 
│ │ │ │   │ └─┬ lru-cache@4.0.2 
│ │ │ │   │   ├── pseudomap@1.0.2 
│ │ │ │   │   └── yallist@2.0.0 
│ │ │ │   ├── is-stream@1.1.0 
│ │ │ │   ├── npm-run-path@1.0.0 
│ │ │ │   ├── path-key@1.0.0 
│ │ │ │   └── strip-eof@1.0.0 
│ │ │ └── widest-line@1.0.0 
│ │ ├─┬ configstore@3.0.0 
│ │ │ ├─┬ dot-prop@4.1.1 
│ │ │ │ └── is-obj@1.0.1 
│ │ │ ├─┬ unique-string@1.0.0 
│ │ │ │ └── crypto-random-string@1.0.0 
│ │ │ └─┬ write-file-atomic@1.3.1 
│ │ │   ├── imurmurhash@0.1.4 
│ │ │   └── slide@1.1.6 
│ │ ├── is-npm@1.0.0 
│ │ ├─┬ latest-version@3.0.0 
│ │ │ └─┬ package-json@3.1.0 
│ │ │   ├─┬ got@6.7.1 
│ │ │   │ ├─┬ create-error-class@3.0.2 
│ │ │   │ │ └── capture-stack-trace@1.0.0 
│ │ │   │ ├── duplexer3@0.1.4 
│ │ │   │ ├── get-stream@3.0.0 
│ │ │   │ ├── is-redirect@1.0.0 
│ │ │   │ ├── is-retry-allowed@1.1.0 
│ │ │   │ ├── lowercase-keys@1.0.0 
│ │ │   │ ├── timed-out@4.0.1 
│ │ │   │ ├── unzip-response@2.0.1 
│ │ │   │ └─┬ url-parse-lax@1.0.0 
│ │ │   │   └── prepend-http@1.0.4 
│ │ │   ├── registry-auth-token@3.1.0 
│ │ │   └── registry-url@3.1.0 
│ │ ├── lazy-req@2.0.0 
│ │ ├── semver-diff@2.1.0 
│ │ └── xdg-basedir@3.0.0 
│ ├─┬ uuid-1345@0.99.6 
│ │ └── macaddress@0.2.8 
│ └─┬ yargs@7.0.2 
│   ├── camelcase@3.0.0 
│   ├─┬ cliui@3.2.0 
│   │ └── wrap-ansi@2.1.0 
│   ├── decamelize@1.2.0 
│   ├── get-caller-file@1.0.2 
│   ├─┬ os-locale@1.4.0 
│   │ └─┬ lcid@1.0.0 
│   │   └── invert-kv@1.0.0 
│   ├─┬ read-pkg-up@1.0.1 
│   │ ├── find-up@1.1.2 
│   │ └─┬ read-pkg@1.1.0 
│   │   ├─┬ load-json-file@1.1.0 
│   │   │ ├─┬ parse-json@2.2.0 
│   │   │ │ └─┬ error-ex@1.3.1 
│   │   │ │   └── is-arrayish@0.2.1 
│   │   │ ├── pify@2.3.0 
│   │   │ └─┬ strip-bom@2.0.0 
│   │   │   └── is-utf8@0.2.1 
│   │   └── path-type@1.1.0 
│   ├── require-directory@2.1.1 
│   ├── require-main-filename@1.0.1 
│   ├── set-blocking@2.0.0 
│   ├─┬ string-width@1.0.2 
│   │ ├── code-point-at@1.1.0 
│   │ └─┬ is-fullwidth-code-point@1.0.0 
│   │   └── number-is-nan@1.0.1 
│   ├── which-module@1.0.0 
│   ├── y18n@3.2.1 
│   └─┬ yargs-parser@5.0.0 
│     └── camelcase@3.0.0 
├── electron-cookies@1.1.0 
├─┬ electron-rebuild@1.5.7 
│ ├─┬ babel-register@6.23.0 
│ │ ├─┬ babel-core@6.23.1 
│ │ │ ├─┬ babel-code-frame@6.22.0 
│ │ │ │ ├── esutils@2.0.2 
│ │ │ │ └── js-tokens@3.0.1 
│ │ │ ├─┬ babel-generator@6.23.0 
│ │ │ │ ├── babel-runtime@6.23.0 
│ │ │ │ ├─┬ detect-indent@4.0.0 
│ │ │ │ │ └─┬ repeating@2.0.1 
│ │ │ │ │   └── is-finite@1.0.2 
│ │ │ │ ├── jsesc@1.3.0 
│ │ │ │ └── trim-right@1.0.1 
│ │ │ ├─┬ babel-helpers@6.23.0 
│ │ │ │ └── babel-runtime@6.23.0 
│ │ │ ├─┬ babel-messages@6.23.0 
│ │ │ │ └── babel-runtime@6.23.0 
│ │ │ ├── babel-runtime@6.23.0 
│ │ │ ├─┬ babel-template@6.23.0 
│ │ │ │ └── babel-runtime@6.23.0 
│ │ │ ├─┬ babel-traverse@6.23.1 
│ │ │ │ ├── babel-runtime@6.23.0 
│ │ │ │ ├── globals@9.16.0 
│ │ │ │ └─┬ invariant@2.2.2 
│ │ │ │   └── loose-envify@1.3.1 
│ │ │ ├─┬ babel-types@6.23.0 
│ │ │ │ ├── babel-runtime@6.23.0 
│ │ │ │ └── to-fast-properties@1.0.2 
│ │ │ ├── babylon@6.16.1 
│ │ │ ├── convert-source-map@1.4.0 
│ │ │ ├── json5@0.5.1 
│ │ │ ├── private@0.1.7 
│ │ │ └── slash@1.0.0 
│ │ ├─┬ babel-runtime@6.23.0 
│ │ │ └── regenerator-runtime@0.10.3 
│ │ ├── core-js@2.4.1 
│ │ ├─┬ home-or-tmp@2.0.0 
│ │ │ └── os-tmpdir@1.0.2 
│ │ └── lodash@4.17.4 
│ ├─┬ babel-runtime@6.18.0 
│ │ └── regenerator-runtime@0.9.6 
│ ├── bluebird@3.5.0 
│ ├── colors@1.1.2 
│ ├─┬ debug@2.6.2 
│ │ └── ms@0.7.2 
│ ├─┬ fs-promise@1.0.0 
│ │ ├── any-promise@1.3.0 
│ │ ├── fs-extra@1.0.0 
│ │ ├─┬ mz@2.6.0 
│ │ │ └── object-assign@4.1.1 
│ │ └─┬ thenify-all@1.6.0 
│ │   └── thenify@3.2.1 
│ ├── node-abi@1.3.3 
│ ├─┬ node-gyp@3.5.0 
│ │ ├── fstream@1.0.11 
│ │ ├─┬ glob@7.1.1 
│ │ │ ├── fs.realpath@1.0.0 
│ │ │ ├─┬ inflight@1.0.6 
│ │ │ │ └── wrappy@1.0.2 
│ │ │ └── once@1.4.0 
│ │ ├── graceful-fs@4.1.11 
│ │ ├─┬ nopt@3.0.6 
│ │ │ └── abbrev@1.1.0 
│ │ ├─┬ npmlog@4.0.2 
│ │ │ ├─┬ are-we-there-yet@1.1.2 
│ │ │ │ └── delegates@1.0.0 
│ │ │ ├── console-control-strings@1.1.0 
│ │ │ └─┬ gauge@2.7.3 
│ │ │   ├── aproba@1.1.1 
│ │ │   ├── has-unicode@2.0.1 
│ │ │   ├── signal-exit@3.0.2 
│ │ │   └── wide-align@1.1.0 
│ │ ├── osenv@0.1.4 
│ │ ├─┬ tar@2.2.1 
│ │ │ └── block-stream@0.0.9 
│ │ └─┬ which@1.2.12 
│ │   └── isexe@1.1.2 
│ ├─┬ ora@0.3.0 
│ │ ├─┬ cli-cursor@1.0.2 
│ │ │ └─┬ restore-cursor@1.0.1 
│ │ │   ├── exit-hook@1.1.1 
│ │ │   └── onetime@1.1.0 
│ │ ├── cli-spinners@0.2.0 
│ │ └── log-symbols@1.0.2 
│ ├── rimraf@2.6.1 
│ ├─┬ spawn-rx@2.0.10 
│ │ ├── lodash.assign@4.2.0 
│ │ └─┬ rxjs@5.2.0 
│ │   └── symbol-observable@1.0.4 
│ └─┬ yargs@3.32.0 
│   ├── camelcase@2.1.1 
│   └── window-size@0.1.4 
├─┬ freedesktop-notifications@1.2.2 
│ └─┬ dbus-native@0.2.0 
│   ├─┬ abstract-socket@1.1.0 
│   │ ├── bindings@1.2.1 
│   │ └── nan@2.5.1 
│   ├─┬ event-stream@3.3.4 
│   │ ├── duplexer@0.1.1 
│   │ ├── from@0.1.3 
│   │ ├── map-stream@0.1.0 
│   │ ├── pause-stream@0.0.11 
│   │ ├── split@0.3.3 
│   │ ├── stream-combiner@0.0.4 
│   │ └── through@2.3.8 
│   ├── put@0.0.6 
│   └─┬ xml2js@0.1.14 
│     └── sax@1.2.2 
├─┬ node-unofficialmxm@2.0.0  (git+https://github.com/Quacky2200/node-unofficialmxm.git#afb1329e0b221bca5326562cd5e8554cf276b046)
│ └─┬ cheerio@0.22.0 
│   ├─┬ css-select@1.2.0 
│   │ ├── boolbase@1.0.0 
│   │ ├── css-what@2.1.0 
│   │ ├── domutils@1.5.1 
│   │ └── nth-check@1.0.1 
│   ├─┬ dom-serializer@0.1.0 
│   │ └── domelementtype@1.1.3 
│   ├── entities@1.1.1 
│   ├─┬ htmlparser2@3.9.2 
│   │ ├── domelementtype@1.3.0 
│   │ ├── domhandler@2.3.0 
│   │ └─┬ readable-stream@2.2.3 
│   │   └── buffer-shims@1.0.0 
│   ├── lodash.assignin@4.2.0 
│   ├── lodash.bind@4.2.1 
│   ├── lodash.defaults@4.2.0 
│   ├── lodash.filter@4.6.0 
│   ├── lodash.flatten@4.4.0 
│   ├── lodash.foreach@4.5.0 
│   ├── lodash.map@4.6.0 
│   ├── lodash.merge@4.6.0 
│   ├── lodash.pick@4.4.0 
│   ├── lodash.reduce@4.6.0 
│   ├── lodash.reject@4.6.0 
│   └── lodash.some@4.6.0 
├─┬ request@2.81.0 
│ ├── aws-sign2@0.6.0 
│ ├── aws4@1.6.0 
│ ├── caseless@0.12.0 
│ ├─┬ combined-stream@1.0.5 
│ │ └── delayed-stream@1.0.0 
│ ├── extend@3.0.0 
│ ├── forever-agent@0.6.1 
│ ├─┬ form-data@2.1.2 
│ │ └── asynckit@0.4.0 
│ ├─┬ har-validator@4.2.1 
│ │ ├── ajv@4.11.4 
│ │ └── har-schema@1.0.5 
│ ├─┬ hawk@3.1.3 
│ │ ├── boom@2.10.1 
│ │ ├── cryptiles@2.0.5 
│ │ ├── hoek@2.16.3 
│ │ └── sntp@1.0.9 
│ ├─┬ http-signature@1.1.1 
│ │ ├── assert-plus@0.2.0 
│ │ ├─┬ jsprim@1.3.1 
│ │ │ ├── extsprintf@1.0.2 
│ │ │ ├── json-schema@0.2.3 
│ │ │ └── verror@1.3.6 
│ │ └─┬ sshpk@1.11.0 
│ │   ├── asn1@0.2.3 
│ │   ├── assert-plus@1.0.0 
│ │   ├── bcrypt-pbkdf@1.0.1 
│ │   ├─┬ dashdash@1.14.1 
│ │   │ └── assert-plus@1.0.0 
│ │   ├── ecc-jsbn@0.1.1 
│ │   ├─┬ getpass@0.1.6 
│ │   │ └── assert-plus@1.0.0 
│ │   ├── jodid25519@1.0.2 
│ │   ├── jsbn@0.1.1 
│ │   └── tweetnacl@0.14.5 
│ ├── is-typedarray@1.0.0 
│ ├── isstream@0.1.2 
│ ├── json-stringify-safe@5.0.1 
│ ├─┬ mime-types@2.1.14 
│ │ └── mime-db@1.26.0 
│ ├── oauth-sign@0.8.2 
│ ├── performance-now@0.2.0 
│ ├── qs@6.4.0 
│ ├── safe-buffer@5.0.1 
│ ├── stringstream@0.0.5 
│ ├─┬ tough-cookie@2.3.2 
│ │ └── punycode@1.4.1 
│ ├── tunnel-agent@0.6.0 
│ └── uuid@3.0.1 
└─┬ sanitize-filename@1.6.1 
  └─┬ truncate-utf8-bytes@1.0.2 
    └── utf8-byte-length@1.0.4 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules/7zip-bin/node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^2.0.2 (node_modules/7zip-bin/node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.0.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ajv-keywords@2.0.1-beta.1 requires a peer of ajv@>=5.0.3-beta.0 but none was installed.
npm ERR! Linux 4.8.0-41-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! dbus@0.2.23 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dbus@0.2.23 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dbus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dbus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dbus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/bin/spotifywebplayer/npm-debug.log
```

As you can see there are two errors, one at the top and one at the bottom. Just wondering if anyone knows what the problem is? I can post the npm-debug.log if needed but I thought it might be too long to post.

**Comment by Quacky2200** [comment]
Did you download a release of 1.0.35 or did you download the source code from GitHub?

Either way, if you wanted to use npm in that directory you will need to prefix `sudo` to the command, however if you installed it from an installer you wouldn't need to install npm repositories. If you were trying to install it manually, it may be best to install it in your home directory so you're not messing around with system files.

**Comment by Jazzelhawk** [comment]
I downloaded the source code from 1.0.35 and wanted to install it manually because I wanted to try changing the user agent as in one of the latest comments in the other issue thread because I have the same problem. I took your advice and installed it in my home directory and I got the dbus node module from the .deb file and npm looks like it installs everything correctly. But now when I try and start the app I get the same error as in #76. 
The only output after running ``npm install`` is
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules/7zip-bin/node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^2.0.2 (node_modules/7zip-bin/node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.0.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
```
Which looks normal, so any advice?

**Comment by Quacky2200** [comment]
Try installing electron-builder with `npm install electron-builder` and then try following these commands from [using native node modules](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md)
```
# Electron's version.
export npm_config_target=1.2.3
# The architecture of Electron, can be ia32 or x64.
export npm_config_arch=x64
export npm_config_target_arch=x64
# Download headers for Electron.
export npm_config_disturl=https://atom.io/download/electron
# Tell node-pre-gyp that we are building for Electron.
export npm_config_runtime=electron
# Tell node-pre-gyp to build module from source code.
export npm_config_build_from_source=true
# Install all dependencies, and store cache to ~/.electron-gyp.
HOME=~/.electron-gyp npm install
```

Afterwards try building with 
`npm build`
If that doesn't work, also try using
`npm run dist`

Despite electron-builder devs saying that building with native modules has the same outcome as creating the distributed installers with their installer, I've found it to be the opposite and using the installer sometimes fixes my dev environment. You can then run the app using
`node main.js`

**Comment by Jazzelhawk** [comment]
For my original problem I actually ended up having to install ``libdbus-glib-1-dev`` and  ``libdbus-1-dev``. 
After running ``npm build`` there is no output, is this normal?
And after running ``npm run dist`` it outputs this:
```
matthew@Aspire-ES1-522:~/spotifywebplayer$ npm run dist

> spotifywebplayer@1.0.30 dist /home/matthew/spotifywebplayer
> build

Error: Config is invalid:
{                                                                                       
  "linux": [                                                                            
    {                                                                                   
      "synopsis": "Unknown option"                                                      
    },                                                                                  
    "Invalid option object"                                                             
  ]                                                                                     
}                                                                                       

Raw validation errors: [                                                                
  {                                                                                     
    "keyword": "additionalProperties",                                                  
    "dataPath": ".linux",                                                               
    "schemaPath": "#/additionalProperties",                                             
    "params": {                                                                         
      "additionalProperty": "synopsis"                                                  
    },                                                                                  
    "message": "should NOT have additional properties"                                  
  },                                                                                    
  {                                                                                     
    "keyword": "type",                                                                  
    "dataPath": ".linux",                                                               
    "schemaPath": "#/properties/linux/anyOf/1/type",                                    
    "params": {                                                                         
      "type": "null"                                                                    
    },                                                                                  
    "message": "should be null"                                                         
  },                                                                                    
  {                                                                                     
    "keyword": "anyOf",                                                                 
    "dataPath": ".linux",                                                               
    "schemaPath": "#/properties/linux/anyOf",                                           
    "params": {},                                                                       
    "message": "should match some schema in anyOf"                                      
  }                                                                                     
]                                                                                       
    at /home/matthew/spotifywebplayer/node_modules/electron-builder/src/util/readPackageJson.ts:151:11                                                                          
From previous event:                                                                    
    at validateConfig (/home/matthew/spotifywebplayer/node_modules/electron-builder/out/util/readPackageJson.js:155:22)                                                         
    at /home/matthew/spotifywebplayer/node_modules/electron-builder/src/packager.ts:129:11                                                                                      
    at Generator.next (<anonymous>)                                                     
    at runCallback (timers.js:666:20)                                                   
    at tryOnImmediate (timers.js:639:5)                                                 
    at processImmediate [as _immediateCallback] (timers.js:611:5)                       
From previous event:                                                                    
    at Packager.build (/home/matthew/spotifywebplayer/node_modules/electron-builder/out/packager.js:272:11)                                                                     
    at /home/matthew/spotifywebplayer/node_modules/electron-builder/src/builder.ts:198:33                                                                                       
    at Generator.next (<anonymous>)                                                     
From previous event:                                                                    
    at build (/home/matthew/spotifywebplayer/node_modules/electron-builder/out/builder.js:70:21)                                                                                
    at Object.<anonymous> (/home/matthew/spotifywebplayer/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3

npm ERR! Linux 4.8.0-41-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dist"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! spotifywebplayer@1.0.30 dist: `build`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the spotifywebplayer@1.0.30 dist script 'build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spotifywebplayer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spotifywebplayer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spotifywebplayer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/matthew/spotifywebplayer/npm-debug.log
```

**Comment by Jazzelhawk** [comment]
The previous error was complaining about the synopsis part of the package.json so I removed that line and the error went away.
Then I got an error about 'spawning' `icns2png` so I had to install `icnsutils`
Then another error about spawning `gm` so installed `graphicsmagick`
Then one about spawning `snapcraft` so installed `snapcraft`
Then a different error about not finding `libreadline.so.6` so installed `libreadline6`
Everything then worked fine running `npm run dist`
Tried `node main.js` and still have `Error: No introspectable` :(
