### ISSUE TITLE
Unable to get prerequisites on my Pine64

### ISSUE THREAD

**Issue by klode82** [Quacky2200/Spotify-Web-Player-for-Linux#86]
Hi,
I'm working hard to install these awesome app on my Pine64:

`Linux pine64 3.10.102-2-pine64-longsleep #66 SMP PREEMPT Sat Jul 16 10:53:13 CEST 2016 aarch64 GNU/Linux`

However, during the execution of script get_prerequisites.sh I got this error:

`/usr/bin/spotifywebplayer/get_prerequisites.sh: 3: /usr/bin/spotifywebplayer/get_prerequisites.sh: Bad substitution
unknown architecture - cannot proceed.
`

How can I resolve this issue?

**Comment by Quacky2200** [comment]
I take it this is the same architecture of a Raspberry Pi, that and the `aarch64` you have given.

Taking this on board you will have to install Node js, Electron and libappindicator-1, dbus and libnotify4 as well as development packages for the libraries (especially for dbus). Then when installing NPM packages you will have to build Electron natively. Afterwards you'll be able to start the program with `node main.js`

**Comment by klode82** [comment]
Thanks for your supply.
NodeJS 7.8.0 OK
Electron is a nodejs package? I've installed it on node_modules into spotifywebplyer, is this correct?
libappindicator-1 0.4.92 OK
dbus 1.22 OK
libnotify4 0.6.2 OK

However, when I start 'node main.js' I got this error:

`/usr/bin/spotifywebplayer/js/backend/properties.js:59
        VERSION: electron.app.getVersion(),
                             ^

TypeError: Cannot read property 'getVersion' of undefined
    at module.exports (/usr/bin/spotifywebplayer/js/backend/properties.js:59:30)
    at Object.<anonymous> (/usr/bin/spotifywebplayer/main.js:8:47)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
`

I think I have some issue with Electron, isn't it?

**Comment by Quacky2200** [comment]
Could you quickly specify which version you're trying to use, is this version 1.0.0?

**Comment by Quacky2200** [comment]
This might actually be that you need to use the electron executable instead of using node. This should be present in `./node_modules/.bin/electron/electron`, then you can just execute with the following `./node_modules/.bin/electron/electron ./`

The command to start Spotify Web Player has changed in the last few releases which is why I had given you the command `node main.js` but this is wrong with this version. Apologies.

**Comment by klode82** [comment]
Yes, I'm trying to use 1.0.0.
When I'm trying to use like you suggest, I got this error:

`debian@pine64:/usr/bin/spotifywebplayer$ sudo ./node_modules/electron/dist/electron ./
./node_modules/electron/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory`

**Comment by Quacky2200** [comment]
You may need to install the libgtk2.0-0 (or development) package

**Comment by klode82** [comment]
Thanks again for your supply. However, I've just libgtk2.0, but 64bit, not 32. I've tried to make a symbolic link for the same library but 64 bit into /usr/lib, but it got me error on ECLASS64.

**Comment by klode82** [comment]
I've changed distro. Now I'm using Ubuntu Xenial 16.04 for Pine64 (aarch64).
into  `get_prerequisistes.sh`I've added this code:
`        "arm64"|"aarch64")
                node_download_link="https://nodejs.org/dist/v6.10.2/node-v6.10.2-linux-armv7l.tar.xz"
                electron_download_link="https://github.com/electron/electron/releases/download/v1.4.16/electron-v1.4.16-linux-arm.zip"
                ;;
`
Then, I've installed electron using this command:

`npm install --arch=aarch64 electron`

But when I use the command:

`node --use_strict main.js`

I got this error:

```
/usr/bin/spotifywebplayer/js/backend/properties.js:59
        VERSION: electron.app.getVersion(),
                             ^

TypeError: Cannot read property 'getVersion' of undefined
    at module.exports.electron (/usr/bin/spotifywebplayer/js/backend/properties.js:59:30)
    at Object.<anonymous> (/usr/bin/spotifywebplayer/main.js:9:47)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```
Someone can help me?

**Comment by SedesGobhani** [comment]
Did this ever get resolved: "Cannot read property 'getVersion' of undefined"?
