### ISSUE TITLE
Sing! Loading error - Cannot read property '1' of null

### ISSUE THREAD

**Issue by Validbit** [Quacky2200/Spotify-Web-Player-for-Linux#88]
Hello,
When trying to show lyrics (Sing!) it crashes while loading and never loads. I haven't found a solution for this or similar error.
More Info:
- Clean install from spotifywebplayer_1.0.42_amd64.deb
- Ubuntu 16.04.3 with Gnome

Error:
`Uncaught Exception:
TypeError: Cannot read property '1' of null
    at Request.request [as _callback] (/opt/Spotify Web Player for Linux/resources/app.asar/node_modules/node-unofficialmxm/index.js:54:94)
    at Request.self.callback (/opt/Spotify Web Player for Linux/resources/app.asar/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/opt/Spotify Web Player for Linux/resources/app.asar/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/opt/Spotify Web Player for Linux/resources/app.asar/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:91:20)`

**Comment by Quacky2200** [comment]
Hi @Validbit,

Thanks for your feedback. It looks like MusixMatch have changed their website which messes up the bot. It would typically expect it to be present in a JSON but have changed it to a list of promises.
